services:
  - type: web
    name: keyfocus
    env: static
    staticPublishPath: .
    pullRequestPreviewsEnabled: true
    routes:
      - type: redirect
        source: /
        destination: /index.html
      - type: rewrite
        source: /details
        destination: /details.html
      - type: rewrite
        source: /generate
        destination: /generate.html
